//
//  AppDelegate.swift
//  FrameworkClientApp
//
//  Created by wregula on 23/04/2019.
//  Copyright © 2019 wregula. All rights reserved.
//

import UIKit

// NOTE: When you do not specify access control for classes / methods / variables they are internal by default.
// IMO it would be better to indicate that you want this class to be internal by adding `internal` keyword ewerywhere
// It's always better to mark a class with access modifier, so anyone knows your intentions :)
@UIApplicationMain
class AppDelegate: UIResponder, UIApplicationDelegate {

    var window: UIWindow?

    func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {
        // NOTE: - \/ comments generated by XCode could be removed as it is something which is not welcome in the codebase.
        // Override point for customization after application launch.
        return true
    }

    // NOTE: Some cleanup - generally when you do not use some methods, you can remove them so a reader is not distracted by something which literally does nothing
    func applicationWillResignActive(_ application: UIApplication) {
         }

    func applicationDidEnterBackground(_ application: UIApplication) {
        }

    func applicationWillEnterForeground(_ application: UIApplication) {
    }

    func applicationDidBecomeActive(_ application: UIApplication) {
    }

    func applicationWillTerminate(_ application: UIApplication) {
    }

}
